.github/workflows/ci.yml
adapter-in/web/build.gradle.kts
build.gradle.kts
core/build.gradle.kts
domain/build.gradle.kts
port-in/build.gradle.kts
port-out/build.gradle.kts

fix: BooJar build 에러 수정

---

adapter-out/rdb/build.gradle.kts
core/build.gradle.kts
core/src/main/kotlin/yapp/rating/Exception.kt
core/src/main/kotlin/yapp/rating/Extension.kt
core/src/main/kotlin/yapp/rating/auth/token/JwtUtils.kt
core/src/main/kotlin/yapp/rating/auth/token/OpaqueTokenUtils.kt
core/src/main/kotlin/yapp/rating/auth/token/TokenUtils.kt
core/src/test/kotlin/yapp/rating/ExtensionTest.kt
core/src/test/kotlin/yapp/rating/auth/token/JwtUtilsTest.kt
core/src/test/kotlin/yapp/rating/auth/token/OpaqueTokenUtilsTest.kt
domain/src/main/kotlin/yapp/rating/auth/Token.kt

Auth-1 Token 관련 기능

---

Dockerfile
adapter-out/rdb/src/main/resources/application-rdb.yml

- [Notion Ticket](https://yapp-workspace.notion.site/Back-sandbox-DB-ae0075802426401fbf03b526a9c7e4c2)
sandbox database 를 세팅했어요
aws rds 를 썼습니다.
계정이나 url 은 [wiki](https://yapp-workspace.notion.site/aws-0f4a3935b49d486aaa83cf3a4acf56f7)에 정리해뒀어요.

sandbox-2: sandbox DB 세팅

---

.gitignore
README.md
adapter-in/web/build.gradle.kts
adapter-in/web/src/main/kotlin/yapp/rating/TestController.kt
adapter-in/web/src/main/kotlin/yapp/rating/boardgame/WebApplication.kt
adapter-in/web/src/test/kotlin/yapp/rating/ControllerTest.kt
adapter-in/web/src/test/kotlin/yapp/rating/TestControllerTest.kt
adapter-in/web/src/test/kotlin/yapp/rating/base/ControllerTest.kt
adapter-in/web/src/test/kotlin/yapp/rating/base/DocumentField.kt
adapter-in/web/src/test/kotlin/yapp/rating/base/DocumentFieldType.kt
adapter-in/web/src/test/kotlin/yapp/rating/base/OpenApiTag.kt
adapter-out/rdb/build.gradle.kts
build.gradle.kts

APIDOC - Base

---

.github/workflows/ci-cd.yml
.github/workflows/dev-ci-cd.yml

- [Notion Ticket](https://yapp-workspace.notion.site/Back-cd-98713236ab4d4ae3a0f2682cac4fcffc)
(ci)/cd 파이프라인을 구축했습니다.
http://3.39.205.168:8080/v1/test
(제가 잘 올라가나 테스트한다고 중간에 response data를 바꿨습니다)
동작 순서는
1. dev 브랜치에 push 되면
1. 이미지 빌드해서 도커 허브에 push 하고
3. aws ec2 에 ssh 로 접속해서 도커허브에서 이미지 땡겨서 컨테이너 띄우는 방식입니다.
처음에는 aws codedeploy 로 해본다고 삽질을 좀 했는데, 누가 요런 편리한 [action](https://github.com/appleboy/ssh-action) 을 만들어놨길래 그냥 이걸 썼습니다.

sandbox-3: sandbox CD 파이프라인 세팅

---

.github/PULL_REQUEST_TEMPLATE.md
adapter-in/web/src/main/kotlin/com/yapp/bol/WebApplication.kt

fix: PR Template 지라로 변경

---

.github/workflows/ci-cd.yml
Dockerfile
adapter-out/rdb/src/main/resources/application-rdb.yml

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-67)
라이브로 해결해서 따로 코멘트는 없습니당

BOL-67 fix: sandbox 배포 안 되는 이슈 수정

---

domain/src/main/kotlin/com/yapp/bol/group/Group.kt
domain/src/main/kotlin/com/yapp/bol/group/member/Member.kt
domain/src/main/kotlin/com/yapp/bol/group/member/MemberList.kt
domain/src/main/kotlin/com/yapp/bol/group/member/MemberRole.kt
domain/src/main/kotlin/com/yapp/bol/group/member/Members.kt
domain/src/test/kotlin/com/yapp/bol/group/GroupTest.kt
domain/src/test/kotlin/com/yapp/bol/member/MemberTest.kt

Reference  
[Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-35)
브랜치 네임이 잘못된걸 발견해 pr close 하고 다시 올립니다
참고 사항  

BOL-35 그룹 생성- 도메인 객체 추가

---

adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupCommandRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupEntity.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupQueryRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupRepository.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberCommandRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberEntity.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberRepository.kt
adapter-out/rdb/src/main/resources/application-rdb.yml
adapter-out/rdb/src/main/resources/sql.ddl/2023_06_06_CREATE_GROUP.sql
adapter-out/rdb/src/main/resources/sql.ddl/2023_06_06_CREATE_MEMBER.sql
domain/src/main/kotlin/com/yapp/bol/group/member/MemberList.kt
port-out/src/main/kotlin/com/yapp/bol/group/GroupCommandRepository.kt
port-out/src/main/kotlin/com/yapp/bol/group/GroupQueryRepository.kt
port-out/src/main/kotlin/com/yapp/bol/group/member/MemberCommandRepository.kt
port-out/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepository.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-35)

BOL-35 그룹 생성- port-out, adapter-out 추가

---

domain/src/main/kotlin/com/yapp/bol/game/Game.kt
domain/src/main/kotlin/com/yapp/bol/game/GameRankType.kt
port-in/src/main/kotlin/com/yapp/bol/game/GameService.kt
port-out/src/main/kotlin/com/yapp/bol/game/GameQueryRepository.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-92)
모듈 별로 나눠서 PR을 하니까 편한 것 같아 적지만 나눠서 올려봅니다.

BOL-92 1. Game Domain 객체

---

adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameEntity.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameRepository.kt
adapter-out/rdb/src/main/resources/sql/ddl/2023_05_14_CREATE_AUTH.sql
adapter-out/rdb/src/main/resources/sql/ddl/2023_05_14_CREATE_USER.sql
adapter-out/rdb/src/main/resources/sql/ddl/2023_06_03_CREATE_FILE.sql
adapter-out/rdb/src/main/resources/sql/ddl/2023_06_13_CREATE_GAME.sql
adapter-out/rdb/src/main/resources/sql/dml/2023_06_13_INSERT_GAMES.sql

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-92)

BOL-92 2.  Game - AdpaterOut

---

adapter-in/web/src/main/kotlin/com/yapp/bol/user/UserController.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/user/dto/MyInfoResponse.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/base/OpenApiTag.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/user/UserControllerTest.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/user/UserClient.kt
core/src/main/kotlin/com/yapp/bol/user/UserServiceImpl.kt
domain/src/main/kotlin/com/yapp/bol/Exception.kt
domain/src/main/kotlin/com/yapp/bol/user/User.kt
port-in/src/main/kotlin/com/yapp/bol/user/UserService.kt
port-out/src/main/kotlin/com/yapp/bol/user/UserQueryRepository.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-112)

BOL-112 내 정보 가져오기

---

adapter-in/web/src/main/kotlin/com/yapp/bol/user/UserController.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/user/dto/MyInfoResponse.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/base/OpenApiTag.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/user/UserControllerTest.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberEntity.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/user/UserClient.kt
adapter-out/rdb/src/main/resources/sql.ddl/2023_06_06_CREATE_MEMBER.sql
core/src/main/kotlin/com/yapp/bol/user/UserServiceImpl.kt
domain/src/main/kotlin/com/yapp/bol/Exception.kt
domain/src/main/kotlin/com/yapp/bol/group/member/GuestMember.kt
domain/src/main/kotlin/com/yapp/bol/group/member/HostMember.kt
domain/src/main/kotlin/com/yapp/bol/group/member/Member.kt
domain/src/main/kotlin/com/yapp/bol/group/member/OwnerMember.kt
domain/src/main/kotlin/com/yapp/bol/group/member/ParticipantMember.kt
domain/src/main/kotlin/com/yapp/bol/pagination/CursorRequest.kt
domain/src/main/kotlin/com/yapp/bol/pagination/CursorResponse.kt
domain/src/main/kotlin/com/yapp/bol/pagination/SimpleCursorRequest.kt
domain/src/main/kotlin/com/yapp/bol/pagination/SimpleCursorResponse.kt
domain/src/main/kotlin/com/yapp/bol/user/User.kt
port-in/src/main/kotlin/com/yapp/bol/user/UserService.kt
port-out/src/main/kotlin/com/yapp/bol/user/UserQueryRepository.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-94)
커서 방식 관련 클래스를 일단 만들긴 했는데 #45 랑 중복되서 이래저래 처리가 필요 할 것 같습니다.

BOL-94-1 맴버 목록 가져오기 기초 작업

---

adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-)
document identifier 수정

그룹 생성 스웨거 오류 해결

---

adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/GroupReponse.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/user/UserController.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/user/dto/JoinedGroupResponse.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/user/UserControllerTest.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupQueryRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupRepository.kt
core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
port-in/src/main/kotlin/com/yapp/bol/group/GroupService.kt
port-out/src/main/kotlin/com/yapp/bol/group/GroupQueryRepository.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-109)

BOL-109 feat: 가입한 그룹 목록 가져오기

---

adapter-in/web/src/main/kotlin/com/yapp/bol/group/GroupController.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupQueryRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupRepository.kt
core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
port-in/src/main/kotlin/com/yapp/bol/group/GroupService.kt
port-out/src/main/kotlin/com/yapp/bol/group/GroupQueryRepository.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-116)

BOL-116 fix: 그룹 소속으로 검색하기

---

adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImpl.kt
adapter-out/rdb/src/test/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImplTest.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-94)

BOL-94 fix: 맴버 조회 시 EmptyList 에러 해결

---

adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameMemberEntity.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchEntity.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-)
FK 에 JoinColumn 안 붙여서 발생한 문제 해결입니다 

jpa OneToOne 연관관계 오류 해결

---

adapter-in/web/src/main/kotlin/com/yapp/bol/auth/AuthController.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/auth/dto/LoginResponse.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/auth/AuthControllerTest.kt
core/src/main/kotlin/com/yapp/bol/onboarding/OnboardingServiceImpl.kt
domain/src/main/kotlin/com/yapp/bol/onboarding/OnboardingType.kt
port-in/src/main/kotlin/com/yapp/bol/onboarding/OnboardingService.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-153)

BOL-153 feat: 로그인 시 남은 온보딩 보여주기

---

adapter-in/web/src/main/kotlin/com/yapp/bol/group/GroupController.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/GroupDetailResponse.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/GroupListResponse.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/GroupReponse.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberRepository.kt
core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
domain/src/main/kotlin/com/yapp/bol/group/Group.kt
domain/src/main/kotlin/com/yapp/bol/group/dto/GroupWithMemberCount.kt
domain/src/main/kotlin/com/yapp/bol/pagination/offset/PaginationOffsetResponse.kt
port-in/src/main/kotlin/com/yapp/bol/group/GroupService.kt
port-out/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepository.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-155)

BOL-155 그룹 상세 정보 보기 API

---

adapter-in/web/src/main/kotlin/com/yapp/bol/user/UserController.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/user/dto/PutUserInfo.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/user/dto/PutUserInfoRequest.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/base/ControllerTest.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/user/UserControllerTest.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/user/UserClient.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/user/UserEntity.kt
core/src/main/kotlin/com/yapp/bol/user/UserServiceImpl.kt
core/src/test/kotlin/com/yapp/bol/validate/NicknameValidatorTest.kt
domain/src/main/kotlin/com/yapp/bol/Exception.kt
domain/src/main/kotlin/com/yapp/bol/group/member/Member.kt
domain/src/main/kotlin/com/yapp/bol/validate/NicknameValidator.kt
domain/src/test/kotlin/com/yapp/bol/member/MemberTest.kt
port-in/src/main/kotlin/com/yapp/bol/user/UserService.kt
port-out/src/main/kotlin/com/yapp/bol/user/UserCommandRepository.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-150)

BOL-150 유저 정보 변경 API (in 온보딩)

---

adapter-in/web/src/main/kotlin/com/yapp/bol/group/GroupController.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/CheckAccessCodeRequest.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/CheckAccessCodeResponse.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt
core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
port-in/src/main/kotlin/com/yapp/bol/group/GroupService.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-160)

BOL-160 feat: 엑세스 코드 검증 API

---

adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberCommandRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberQueryRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberRepository.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchCommandRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchRepository.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/member/MatchMemberRepository.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonCommandRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonQueryRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonRepository.kt
port-out/src/main/kotlin/com/yapp/bol/game/member/GameMemberCommandRepository.kt
port-out/src/main/kotlin/com/yapp/bol/game/member/GameMemberQueryRepository.kt
port-out/src/main/kotlin/com/yapp/bol/match/MatchCommandRepository.kt
port-out/src/main/kotlin/com/yapp/bol/season/SeasonCommandRepository.kt
port-out/src/main/kotlin/com/yapp/bol/season/SeasonQueryRepository.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-95)

BOL-95 매치 기록 > port-out, adapter-out 추가

---

adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberCommandRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberQueryRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberRepository.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchCommandRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchRepository.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/member/MatchMemberRepository.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonCommandRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonQueryRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonRepository.kt
domain/src/main/kotlin/com/yapp/bol/game/member/GameMember.kt
domain/src/main/kotlin/com/yapp/bol/match/Match.kt
domain/src/main/kotlin/com/yapp/bol/match/member/MatchMember.kt
domain/src/main/kotlin/com/yapp/bol/season/Season.kt
port-out/src/main/kotlin/com/yapp/bol/game/member/GameMemberCommandRepository.kt
port-out/src/main/kotlin/com/yapp/bol/game/member/GameMemberQueryRepository.kt
port-out/src/main/kotlin/com/yapp/bol/match/MatchCommandRepository.kt
port-out/src/main/kotlin/com/yapp/bol/season/SeasonCommandRepository.kt
port-out/src/main/kotlin/com/yapp/bol/season/SeasonQueryRepository.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-95)

BOL-95 매치 기록 > 도메인 클래스 추가

---

adapter-out/rdb/src/main/resources/sql/dml/2023_06_13_INSERT_GAMES.sql
domain/src/main/kotlin/com/yapp/bol/file/FilePurpose.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-)

BOL-188 feat: File Purpose에 Game 이미지 추가

---

adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameClient.kt
core/src/main/kotlin/com/yapp/bol/game/GameServiceImpl.kt
core/src/main/kotlin/com/yapp/bol/game/member/GameMemberServiceImpl.kt
domain/src/main/kotlin/com/yapp/bol/Exception.kt
domain/src/main/kotlin/com/yapp/bol/game/member/GameMember.kt
port-in/src/main/kotlin/com/yapp/bol/game/GameService.kt
port-out/src/main/kotlin/com/yapp/bol/game/GameQueryRepository.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-95-6)

BOL-95 매치 기록 > game 최소 인원 검증 로직 추가

---

.github/workflows/ci-cd-sandbox.yml

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-367)
* github secret, variable 바꿨습니다
* 변경된 포트 맞춰서 수정했어요

BOL-367 Sandbox 파이프라인 수정

---

adapter-in/web/src/main/kotlin/com/yapp/bol/TestController.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/TestControllerTest.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-)

health check API 에 phase 체크용 기능 추가

---

adapter-in/web/src/main/kotlin/com/yapp/bol/game/dto/GameResponse.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/group/GroupController.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/GroupDetailResponse.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/game/GameControllerTest.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameClient.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameRepository.kt
core/src/main/kotlin/com/yapp/bol/game/GameServiceImpl.kt
core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
domain/src/main/kotlin/com/yapp/bol/game/Game.kt
port-in/src/main/kotlin/com/yapp/bol/game/GameService.kt
port-in/src/main/kotlin/com/yapp/bol/group/GroupService.kt
port-out/src/main/kotlin/com/yapp/bol/game/GameQueryRepository.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-339)

BOL-339: 그룹 상세보기 화면 - 자주하는 게임 목록

---

adapter-in/web/src/main/kotlin/com/yapp/bol/file/FileController.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/group/member/MemberController.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/group/member/dto/JoinGroupRequest.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/group/member/MemberControllerTest.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/CustomMemberRepository.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/CustomMemberRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberCommandRepositoryImpl.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberEntity.kt
adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImpl.kt
adapter-out/rdb/src/test/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImplTest.kt
core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
core/src/main/kotlin/com/yapp/bol/group/member/MemberServiceImpl.kt
core/src/main/kotlin/com/yapp/bol/user/UserServiceImpl.kt
core/src/test/kotlin/com/yapp/bol/group/GroupServiceImplTest.kt
domain/src/main/kotlin/com/yapp/bol/Exception.kt
domain/src/main/kotlin/com/yapp/bol/group/member/Member.kt
domain/src/main/kotlin/com/yapp/bol/group/member/dto/PaginationCursorMemberRequest.kt
domain/src/main/kotlin/com/yapp/bol/validate/NicknameValidator.kt
port-in/src/main/kotlin/com/yapp/bol/group/dto/JoinGroupDto.kt
port-out/src/main/kotlin/com/yapp/bol/group/member/MemberCommandRepository.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-29)

BOL-29 feat: 게스트 연동 기능 추가

---

adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupQueryRepositoryImpl.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-372)
그룹 리스트 조회 pageable 에 sort 조건 추가

BOL-372 feat: 그룹 목록 리스트 최신순으로 정렬

---

adapter-in/web/build.gradle.kts
adapter-in/web/src/main/kotlin/com/yapp/bol/TestController.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/utils/ApiMinVersion.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/utils/ForceUpdateAspect.kt
domain/src/main/kotlin/com/yapp/bol/Exception.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-366)

BOL-366 feat: 강제 업데이트 Annotation 추가

---

adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/LeaderBoardResponse.kt
adapter-in/web/src/main/kotlin/com/yapp/bol/group/member/MemberController.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/base/DocumentField.kt
adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt

- [Jira Ticket](https://yapp22-aos2.atlassian.net/browse/BOL-362)

BOL-362 feat: 리더보드에 User Id 추가
